### PR TITLE
feat: angular 7

### PR DESCRIPTION
**Pull request by osnoser1**

### CODE REVIEW

**Comment by serhiisol** [comment]
Thanks for the PR. Could you bump package.json version so we can also release it ?

**Comment by osnoser1** [comment]
Done @serhiisol 😄

**Comment by gonmedtara** [comment]
How can i use this feat !

**Comment by serhiisol** [comment]
Once I release it you'll be able to use it :) I'm going to release it tonight.

**Comment by serhiisol** [comment]
Done, library is released :D

**Pull request merged**
