### PR TITLE
added support for lastInterruptedURL

### PR DESCRIPTION
**Pull request by smnbbrv**
implements #28

### CODE REVIEW

**Comment by serhiisol** [comment]
Hi @smnbbrv. Thanks for the PR. What do you think if `lastInterruptedUrl` will be moved to the `AuthService`? For me that looks much better, cause in best case scenarios, guards shouldn't be injected anywhere else but service can be because it has to be implemented first. :)

**Comment by serhiisol** [comment]
Under 
```moved to the AuthService
```
I meant add necessary fields/methods to the interface `AuthService` and give an option to implement this in the actual class. From my perspective that sounds better than guard.

**Comment by smnbbrv** [comment]
please check updated version

**Comment by serhiisol** [comment]
One small thing, what about the following:
```typescript
setLastInterruptedUri(urI: string): void {
}
```
That basically means that you don't have to define any variables in the interface, but just call the method to save it. Maybe also remove that if something specific occurs.

**Comment by serhiisol** [comment]
alright :)

**Comment by serhiisol** [comment]
Closed in favor of #31

**Comment by serhiisol** [comment]
I took stuff from your PR and prepared new, with discussed adjustments :)

**Pull request closed without merging**
